services:
  - type: web
    runtime: docker
    name: server
    repo: https://github.com/aryaniyaps/python-graphql-relay-todos.git # Default: Repo containing render.yaml
    rootDir: server # Default: Repo root
    envVars:
      - key: SERVER_DEBUG
        value: "false"
      - key: SERVER_ENVIRONMENT
        value: "production"
      - key: SERVER_DATABASE_POOL_SIZE
        value: "20"
      - key: SERVER_HOST
        value: 127.0.0.1
      - key: SERVER_PORT
        value: 8000
      - key: SERVER_LOG_LEVEL
        value: "INFO"
      - key: SERVER_CORS_ALLOW_ORIGINS
        value: "["http://localhost:8080", "http://127.0.0.1:8080"]"
      - key: SERVER_DATABASE_URL
        fromDatabase: # Reference a property of a database (see available properties below)
          name: todos_db
          property: connectionString
      - key: SERVER_DATABASE_TEST_URL
        fromDatabase: # Reference a property of a database (see available properties below)
          name: todos_db
          property: connectionString

  - type: web
    runtime: docker
    name: client
    repo: https://github.com/aryaniyaps/python-graphql-relay-todos.git # Default: Repo containing render.yaml
    rootDir: client # Default: Repo root
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: VITE_API_URL
        value: "http://localhost:8000/graphql/"

databases:
  # A database with a read replica
  - name: elephant
    databaseName: todos_db # Optional (Render may add a suffix)
    user: adrian # Optional
    ipAllowList: # Optional (defaults to allow all)
      - source: 203.0.113.4/30
        description: office
      - source: 198.51.100.1
        description: home
